#+TITLE: Elixir and Phoenix Framework
#+SUBTITLE: 3era Session
#+DATE: 2016/05/29
#+AUTHOR: Albert Castellano Moreno
#+EMAIL: acastemoreno@gmail.com
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:nil p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 24.4.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: es
#+SELECT_TAGS: export

#+GITHUB: http://github.com/acastemoreno

#+FAVICON: images/phoenix.svg
#+ICON: images/phoenix.svg
#+HASHTAG: #elixir #amiguitos #makerlab



* Elixir Language
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:
** Pattern matching
En elixir el simbolo igual no es una asignación. En su lugar es una afirmacion. Tiene exito si Elixir puede encontrar una manera de hacer que el lado izquiero igual al lado derecho. Elixir llama al simbolo = operador match.
#+BEGIN_SRC elixir
iex> list = [1, 2, 3]
[1, 2, 3]
iex> [a, 2, b ] = list
[1, 2, 3]
iex> a
1
iex> b
3
#+END_SRC
** Variables se enlazan una sola vez (por Match)
Las variables pueden enlazarse nuevamente con un nuevo valor en un subsecuente math, el actual valor no participa del match. 
#+BEGIN_SRC elixir
iex> a = 1
1
iex> [1, a, 3] = [1, 2, 3]
[1, 2, 3]
iex> a
2
#+END_SRC
** 
Si queremos forzar a Elixir que use el actual valor de una variable en un Pattern matching agregamos el prefijo ^
#+BEGIN_SRC elixir
iex> a = 1
1
iex> [^a, 2, 3 ] = [ 1, 2, 3 ] # use existing value of a
[1, 2, 3]
iex> a = 2
2
iex> [ ^a, 2 ] = [ 1, 2 ]
  ** (MatchError) no match of right hand side value: [1, 2]
#+END_SRC
* Elixir Language
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:
* Thank You ˊ・ω・ˋ
  :PROPERTIES:
  :SLIDE: thank-you-slide segue
  :ASIDE: right
  :ARTICLE: flexbox vleft auto-fadein
  :END:

* Footnotes

[fn:1] Footnote is in here!